# -*- coding: utf-8 -*-
"""reporter_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpPqcIcMlaoNrmjycPoS6DLDIObtsCV0
"""

# reporter_service.py
from crewai import Agent, AgentExecutor
from fastapi import FastAPI
from pydantic import BaseModel

class IncidentAnalysis(BaseModel):
    root_cause: str
    trigger: str
    consequence: str

class Report(IncidentAnalysis):
    risk_summary: str
    recommendations: str

app = FastAPI(title="Incident Report Service")
executor = AgentExecutor([Agent(name="ReporterAgent")])

@app.post("/report", response_model=Report)
def generate_report(analysis: IncidentAnalysis):
    """
    输入：{"root_cause":..., "trigger":..., "consequence":...}
    返回：risk_summary + recommendations
    """
    result = executor.run_agent("ReporterAgent", analysis.dict())
    return Report(**result)